<a href="https://colab.research.google.com/github/009vinaysharma/AWS-ML-Arya/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Introduction to Pandas

## Aim
To study the basics of the Pandas library.

## Theory
Pandas is an open-source Python library used for data manipulation and analysis.
It provides powerful data structures such as **Series** and **DataFrame**.

## Requirements
- Python
- Pandas
- Jupyter Notebook

## Code
```python
import pandas as pd
```

## Output
Pandas library imported successfully.

## Conclusion
Pandas is successfully imported and ready for data analysis.

# Pandas

## Aim
To study the Pandas library and understand its features for data manipulation and analysis.

## Introduction
Pandas is an open-source Python library used for data analysis and data manipulation. It provides fast, flexible, and efficient data structures for working with structured data.

## Features of Pandas
- Easy handling of missing data.
- Fast and efficient data analysis.
- Supports reading and writing data in various formats such as CSV, Excel, JSON, and SQL.
- Powerful data filtering, sorting, and grouping.
- Built-in statistical and data analysis functions.
- Data cleaning and preprocessing support.
- Time series analysis support.

## Applications
- Data Analysis
- Data Cleaning
- Data Visualization
- Machine Learning
- Business Intelligence
- Financial Data Analysis

## Advantages
- Easy to learn and use.
- High performance.
- Integrates well with NumPy and Matplotlib.
- Supports large datasets.
- Provides powerful data manipulation tools.

## Conclusion
Pandas is one of the most important Python libraries for data analysis. It simplifies working with structured data and is widely used in data science, machine learning, and analytics.

#  Creating a Pandas Series

## Aim
To create a Pandas Series.

## Code
```python
import pandas as pd

data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print(series)
```

## Conclusion
A one-dimensional Pandas Series is created successfully.

#  Creating a DataFrame

## Aim
To create a Pandas DataFrame.

## Code
```python
import pandas as pd

data = {
    "Name": ["Vinay", "Rahul", "Aman"],
    "Age": [21, 22, 20],
    "City": ["Jaipur", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)
```

## Conclusion
A DataFrame is created successfully.

#  Reading a CSV File

## Aim
To read data from a CSV file using Pandas.

## Code
```python
import pandas as pd

df = pd.read_csv("students.csv")
df.head()
```

## Conclusion
The CSV file is successfully loaded into a DataFrame.

In [ ]:
import pandas as pd
l = [10,20,30,40,50] # list
df = pd.Series(l) # use list in pd
print(df)


# example data
df = pd.Series(data=l)
print(df)

# example index
df = pd.Series(data=l , index=['nikhil','devendra','raj','hello','unknown'])
print(df)

# example key = index | value = value
d = {'nikhil':10,'devendra':20,'raj':30,'hello':40,'unknown':50}
df = pd.Series(data=d)
print(df)

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64
nikhil      10
devendra    20
raj         30
hello       40
unknown     50
dtype: int64
nikhil      10
devendra    20
raj         30
hello       40
unknown     50
dtype: int64

In [ ]:
l = [10,20,30,40,50,60] #List
df = pd.Series(l)
df.iloc[0] = 99
print(df)
print(l)

0    99
1    20
2    30
3    40
4    50
5    60
dtype: int64
[10, 20, 30, 40, 50, 60]

In [ ]:
import pandas as pd
data = {
    "name":['nikhli','raj','devendra','hello'],
    "age":[10,20,30,40]
}
# 1D representation
df = pd.Series(data)
print(df)

# 2D representation
df = pd.DataFrame(data)
print(df)

name    [nikhli, raj, devendra, hello]
age                   [10, 20, 30, 40]
dtype: object
       name  age
0    nikhli   10
1       raj   20
2  devendra   30
3     hello   40

In [ ]:
import pandas as pd
data =[['devendra',10],['nikhil',20],['raj',30],['hello',40]]
df = pd.DataFrame(data)
print(df)

# Add Column
df = pd.DataFrame(data,columns=['name','age'])
print(df)

# Add indexing name
df = pd.DataFrame(data,index=['a','b','c','d'])
print(df)

          0   1
0  devendra  10
1    nikhil  20
2       raj  30
3     hello  40
       name  age
0  devendra   10
1    nikhil   20
2       raj   30
3     hello   40
          0   1
a  devendra  10
b    nikhil  20
c       raj  30
d     hello  40

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/009vinaysharma/AWS-ML-Arya/main/file.csv"
df = pd.read_csv(url)
print(df)

#github csv file export
df.to_csv("file1.csv")

       name gender
0     vinay   male
1       raj   male
2  devendra   male
3     hello   male

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/009vinaysharma/AWS-ML-Arya/main/file.xlsx"
df = pd.read_excel(url)
print(df)
# jason file
url = "https://raw.githubusercontent.com/009vinaysharma/AWS-ML-Arya/main/data%20(1).json"
df1 = pd.read_json(url)
print(df1)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male
       name  age
0     vinay   21
1  devendra   20
2    hemant   19
3     hello   40

In [ ]:
# excel file
import pandas as pd
url = "https://raw.githubusercontent.com/009vinaysharma/AWS-ML-Arya/main/file.xlsx"
df = pd.read_excel(url)
print(df)
#github excel file export
df.to_excel("file1.xlsx")


# jason file
url = "https://raw.githubusercontent.com/009vinaysharma/AWS-ML-Arya/main/data%20(1).json"
df1 = pd.read_json(url)
print(df1)
#github jason file export
df1.to_json("file2.json")

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male
       name  age
0     vinay   21
1  devendra   20
2    hemant   19
3     hello   40

# Pandas DataFrame Operations

## Common DataFrame Operations

1. **head()** – Displays the first 5 rows of the DataFrame.
2. **tail()** – Displays the last 5 rows of the DataFrame.
3. **info()** – Shows information about the DataFrame (columns, data types, non-null values, memory usage).
4. **describe()** – Generates summary statistics for numerical columns.
5. **rename()** – Renames column names or index labels.
6. **shape** – Returns the number of rows and columns in the DataFrame.

In [ ]:
import pandas as pd

data = {
    "experience": [1,2,3,4,5,6,7,8,9,10],
    "salary": [100,200,300,400,500,600,700,800,900,1000]
}
#frame
df = pd.DataFrame(data)
df

   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000

In [ ]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]
}
# data frame
df = pd.DataFrame(data)
# print(df)

# head -> starting 5 rows
print(df.head())

# head -> starting 2 rows
print(df.head(2))

# head -> negative
print(df.head(-3))

   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
   experience  salary
0           1     100
1           2     200
   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
5           6     600
6           7     700

In [ ]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)
# tail
print(df.tail())

# tail 3
print(df.tail(3))

# tail negative number
print(df.tail(-2))

   experience  salary
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000
   experience  salary
7           8     800
8           9     900
9          10    1000
   experience  salary
2           3     300
3           4     400
4           5     500
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000

In [ ]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)

# shape
print(df.shape)

#info
print(df.info())

(10, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   experience  10 non-null     int64
 1   salary      10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes
None

In [24]:
import numpy as np
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10,np.nan],
    "salary":[np.nan,100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)
#info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   experience  10 non-null     float64
 1   salary      10 non-null     float64
dtypes: float64(2)
memory usage: 308.0 bytes
None

In [30]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10,np.nan],
    "salary":[np.nan,100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)

#rename
df.rename(columns={'experience':'hands_on_experience'},inplace=True)
print(df)

    hands_on_experience  salary
0                   1.0     NaN
1                   2.0   100.0
2                   3.0   200.0
3                   4.0   300.0
4                   5.0   400.0
5                   6.0   500.0
6                   7.0   600.0
7                   8.0   700.0
8                   9.0   800.0
9                  10.0   900.0
10                  NaN  1000.0

In [ ]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10,np.nan],
    "salary":[np.nan,100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)

#rename
df.rename(columns={'experience':'hands_on_experience','salary':'Amount'},inplace=True)
print(df)

In [23]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]
}
df = pd.DataFrame(data)
print(df.describe())  # describe
print(df.describe(include='all'))  # describe all

       experience       salary
count    10.00000    10.000000
mean      5.50000   550.000000
std       3.02765   302.765035
min       1.00000   100.000000
25%       3.25000   325.000000
50%       5.50000   550.000000
75%       7.75000   775.000000
max      10.00000  1000.000000
       experience       salary
count    10.00000    10.000000
mean      5.50000   550.000000
std       3.02765   302.765035
min       1.00000   100.000000
25%       3.25000   325.000000
50%       5.50000   550.000000
75%       7.75000   775.000000
max      10.00000  1000.000000

In [5]:
#all 6 operation perform
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206, 207, 208],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja", "Rohit", "Anjali"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT", "HR", "Finance"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000, 45000, 62000],
    "Experience": [3, 2, 6, 4, 5, 8, 1, 7],
    "City": ["Jaipur", "Delhi", "Mumbai", "Pune", "Chandigarh", "Jaipur", "Lucknow", "Indore"]
}

df = pd.DataFrame(data)

print(df)

# 1. head() - First 5 rows
print("1. HEAD()")
print(df.head())

# 2. tail() - Last 5 rows
print("\n2. TAIL()")
print(df.tail())

# 3. info() - DataFrame information
print("\n3. INFO()")
df.info()

# 4. describe() - Statistical summary
print("\n4. DESCRIBE()")
print(df.describe())

# 5. rename() - Rename column
print("\n5. RENAME()")
df.rename(columns={"Salary": "Income"}, inplace=True)
print(df.head())

# 6. shape - Number of rows and columns
print("\n6. SHAPE")
print(df.shape)

   Emp_ID    Name Department  Salary  Experience        City
0     201   Rahul         IT   55000           3      Jaipur
1     202   Priya         HR   42000           2       Delhi
2     203   Karan    Finance   65000           6      Mumbai
3     204   Sneha  Marketing   48000           4        Pune
4     205    Aman      Sales   53000           5  Chandigarh
5     206   Pooja         IT   70000           8      Jaipur
6     207   Rohit         HR   45000           1     Lucknow
7     208  Anjali    Finance   62000           7      Indore
1. HEAD()
   Emp_ID   Name Department  Salary  Experience        City
0     201  Rahul         IT   55000           3      Jaipur
1     202  Priya         HR   42000           2       Delhi
2     203  Karan    Finance   65000           6      Mumbai
3     204  Sneha  Marketing   48000           4        Pune
4     205   Aman      Sales   53000           5  Chandigarh

2. TAIL()
   Emp_ID    Name Department  Salary  Experience        City
3     204   Sneha  Marketing   48000           4        Pune
4     205    Aman      Sales   53000           5  Chandigarh
5     206   Pooja         IT   70000           8      Jaipur
6     207   Rohit         HR   45000           1     Lucknow
7     208  Anjali    Finance   62000           7      Indore

3. INFO()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      8 non-null      int64
 1   Name        8 non-null      object
 2   Department  8 non-null      object
 3   Salary      8 non-null      int64
 4   Experience  8 non-null      int64
 5   City        8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

4. DESCRIBE()
          Emp_ID        Salary  Experience
count    8.00000      8.000000     8.00000
mean   204.50000  55000.000000     4.50000
std      2.44949   9971.387638     2.44949
min    201.00000  42000.000000     1.00000
25%    202.75000  47250.000000     2.75000
50%    204.50000  54000.000000     4.50000
75%    206.25000  62750.000000     6.25000
max    208.00000  70000.000000     8.00000

5. RENAME()
   Emp_ID   Name Department  Income  Experience        City
0     201  Rahul         IT   55000           3      Jaipur
1     202  Priya         HR   42000           2       Delhi
2     203  Karan    Finance   65000           6      Mumbai
3     204  Sneha  Marketing   48000           4        Pune
4     205   Aman      Sales   53000           5  Chandigarh

6. SHAPE
(8, 6)

# Operations on Columns

1. Display a single column.
2. Display multiple columns.
3. Rename a column.
4. Add a new column.
5. Delete a column.
6. Update/Modify column values.

In [12]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df)

   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

In [14]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
# 1. Display a single column (select cols)
print(df["Name"])
print(df["Emp_ID"])

# 2. Display multiple columns
print(df[["Name", "Department"]])

0    Rahul
1    Priya
2    Karan
3    Sneha
4     Aman
5    Pooja
Name: Name, dtype: object
0    201
1    202
2    203
3    204
4    205
5    206
Name: Emp_ID, dtype: int64
    Name Department
0  Rahul         IT
1  Priya         HR
2  Karan    Finance
3  Sneha  Marketing
4   Aman      Sales
5  Pooja         IT

In [30]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
# 3.rename a column
df.rename(columns={"Salary": "Income"}, inplace=True)
print(df)

   Emp_ID   Name Department  Income  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

In [29]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
# 4. Add a new column
df["City"] = ["Jaipur", "Delhi", "Mumbai", "Pune", "Chandigarh", "Jaipur"]
print(df)

   Emp_ID   Name Department  Salary  Experience        City
0     201  Rahul         IT   55000           3      Jaipur
1     202  Priya         HR   42000           2       Delhi
2     203  Karan    Finance   65000           6      Mumbai
3     204  Sneha  Marketing   48000           4        Pune
4     205   Aman      Sales   53000           5  Chandigarh
5     206  Pooja         IT   70000           8      Jaipur

In [26]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
# 5. Delete columns
df.drop(columns=["Experience"], inplace=True)
print(df)

# delete multiple columns
df.drop(columns=["Emp_ID", "Salary"], inplace=True)
print(df)

   Emp_ID   Name Department  Salary
0     201  Rahul         IT   55000
1     202  Priya         HR   42000
2     203  Karan    Finance   65000
3     204  Sneha  Marketing   48000
4     205   Aman      Sales   53000
5     206  Pooja         IT   70000
    Name Department
0  Rahul         IT
1  Priya         HR
2  Karan    Finance
3  Sneha  Marketing
4   Aman      Sales
5  Pooja         IT

In [27]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
# 4. Add a new column
df["City"] = ["Jaipur", "Delhi", "Mumbai", "Pune", "Chandigarh", "Jaipur"]
print(df)

#drop cols
df.drop(columns=["Experience"],axis=1,inplace=True)
print(df)

# drop multi cols
df.drop(columns=["City","Salary"],axis=1,inplace=True)
print(df)

   Emp_ID   Name Department  Salary  Experience        City
0     201  Rahul         IT   55000           3      Jaipur
1     202  Priya         HR   42000           2       Delhi
2     203  Karan    Finance   65000           6      Mumbai
3     204  Sneha  Marketing   48000           4        Pune
4     205   Aman      Sales   53000           5  Chandigarh
5     206  Pooja         IT   70000           8      Jaipur
   Emp_ID   Name Department  Salary        City
0     201  Rahul         IT   55000      Jaipur
1     202  Priya         HR   42000       Delhi
2     203  Karan    Finance   65000      Mumbai
3     204  Sneha  Marketing   48000        Pune
4     205   Aman      Sales   53000  Chandigarh
5     206  Pooja         IT   70000      Jaipur
   Emp_ID   Name Department
0     201  Rahul         IT
1     202  Priya         HR
2     203  Karan    Finance
3     204  Sneha  Marketing
4     205   Aman      Sales
5     206  Pooja         IT

In [28]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

# 6. Update/Modify column values
df["Salary"] = df["Salary"] * 1.1  # Increase salary by 10%
print(df)
df["Name"] = df["Name"].str.upper()  # Convert names to uppercase
print(df)

   Emp_ID   Name Department   Salary  Experience
0     201  Rahul         IT  60500.0           3
1     202  Priya         HR  46200.0           2
2     203  Karan    Finance  71500.0           6
3     204  Sneha  Marketing  52800.0           4
4     205   Aman      Sales  58300.0           5
5     206  Pooja         IT  77000.0           8
   Emp_ID   Name Department   Salary  Experience
0     201  RAHUL         IT  60500.0           3
1     202  PRIYA         HR  46200.0           2
2     203  KARAN    Finance  71500.0           6
3     204  SNEHA  Marketing  52800.0           4
4     205   AMAN      Sales  58300.0           5
5     206  POOJA         IT  77000.0           8

# Operations on Rows (loc & iloc)

1. `loc[row, "column"]` – Get a single value using row label and column name.
2. `loc[row]` – Get a complete row.
3. `loc[[row1, row2]]` – Get multiple rows.
4. `loc[[rows], ["col1", "col2"]]` – Get multiple rows and selected columns.
5. `iloc[row_position, column_position]` – Get a single value using index positions.
6. `iloc[row_position]` – Get a complete row using position.
7. `iloc[[row1, row2]]` – Get multiple rows using positions.
8. `iloc[[rows], [cols]]` – Get selected rows and columns using positions.
9. `iloc[[rows], [col]]` – Get a specific column from selected rows.
10. `iloc[[rows], col]` – Get a column as a Series.
11. `iloc[start:end]` – Get rows using slicing.

In [31]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df)

   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

In [32]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print(df.loc[0, "Name"])

Rahul

In [33]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print(df.loc[2])

Emp_ID            203
Name            Karan
Department    Finance
Salary          65000
Experience          6
Name: 2, dtype: object

In [34]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.loc[[1, 3]])

   Emp_ID   Name Department  Salary  Experience
1     202  Priya         HR   42000           2
3     204  Sneha  Marketing   48000           4

In [35]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print(df.loc[[0, 2], ["Name", "Salary"]])

    Name  Salary
0  Rahul   55000
2  Karan   65000

In [36]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[1, 2])

HR

In [37]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}
df = pd.DataFrame(data)
print(df.iloc[4])

Emp_ID          205
Name           Aman
Department    Sales
Salary        53000
Experience        5
Name: 4, dtype: object

In [39]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[[0, 5]])

   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
5     206  Pooja         IT   70000           8

In [40]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[[1, 4], [1, 3]])

    Name  Salary
1  Priya   42000
4   Aman   53000

In [41]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[[0, 2], [0]])

   Emp_ID
0     201
2     203

In [42]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[[1, 2], 0])

1    202
2    203
Name: Emp_ID, dtype: int64

In [43]:
import pandas as pd

data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)
print(df.iloc[0:3])

   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6

In [44]:
import pandas as pd

# Create DataFrame
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

# =====================================================
# 1. loc[] - Get Single Value
# =====================================================
print("\n1. loc[] - Get Single Value")
print(df.loc[0, "Name"])

# =====================================================
# 2. loc[] - Get Complete Row
# =====================================================
print("\n2. loc[] - Get Complete Row")
print(df.loc[2])

# =====================================================
# 3. loc[] - Get Multiple Rows
# =====================================================
print("\n3. loc[] - Get Multiple Rows")
print(df.loc[[1, 3]])

# =====================================================
# 4. loc[] - Get Multiple Rows and Columns
# =====================================================
print("\n4. loc[] - Get Multiple Rows and Columns")
print(df.loc[[0, 2], ["Name", "Salary"]])

# =====================================================
# 5. iloc[] - Get Single Value
# =====================================================
print("\n5. iloc[] - Get Single Value")
print(df.iloc[1, 2])

# =====================================================
# 6. iloc[] - Get Complete Row
# =====================================================
print("\n6. iloc[] - Get Complete Row")
print(df.iloc[4])

# =====================================================
# 7. iloc[] - Get Multiple Rows
# =====================================================
print("\n7. iloc[] - Get Multiple Rows")
print(df.iloc[[0, 5]])

# =====================================================
# 8. iloc[] - Get Multiple Rows and Columns
# =====================================================
print("\n8. iloc[] - Get Multiple Rows and Columns")
print(df.iloc[[1, 4], [1, 3]])

# =====================================================
# 9. iloc[] - Get First Column from Selected Rows
# =====================================================
print("\n9. iloc[] - Get First Column from Selected Rows")
print(df.iloc[[0, 2], [0]])

# =====================================================
# 10. iloc[] - Get Column as Series
# =====================================================
print("\n10. iloc[] - Get Column as Series")
print(df.iloc[[1, 2], 0])

# =====================================================
# 11. iloc[] - Slice Rows
# =====================================================
print("\n11. iloc[] - Slice Rows")
print(df.iloc[0:3])

Original DataFrame
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

1. loc[] - Get Single Value
Rahul

2. loc[] - Get Complete Row
Emp_ID            203
Name            Karan
Department    Finance
Salary          65000
Experience          6
Name: 2, dtype: object

3. loc[] - Get Multiple Rows
   Emp_ID   Name Department  Salary  Experience
1     202  Priya         HR   42000           2
3     204  Sneha  Marketing   48000           4

4. loc[] - Get Multiple Rows and Columns
    Name  Salary
0  Rahul   55000
2  Karan   65000

5. iloc[] - Get Single Value
HR

6. iloc[] - Get Complete Row
Emp_ID          205
Name           Aman
Department    Sales
Salary        53000
Experience        5
Name: 4, dtype: object

7. iloc[] - Get Multiple Rows
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
5     206  Pooja         IT   70000           8

8. iloc[] - Get Multiple Rows and Columns
    Name  Salary
1  Priya   42000
4   Aman   53000

9. iloc[] - Get First Column from Selected Rows
   Emp_ID
0     201
2     203

10. iloc[] - Get Column as Series
1    202
2    203
Name: Emp_ID, dtype: int64

11. iloc[] - Slice Rows
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6

# Filter DataFrame

1. Filter using a single condition.
2. Filter using multiple conditions (AND).
3. Filter using multiple conditions (OR).
4. Filter using `isin()`.
5. Filter using `between()`.
6. Filter using string methods (`startswith()`).

In [46]:
# filter
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)
# filter one greater
print(df[df['Emp_ID'] > 104])

# 106
print(df[df['Emp_ID'] == 106])

# 30000 to 50000
# print(df[(condition one) & (condition 2)])
print(df[(df['Salary']> 30000) & (df['Salary'] < 50000)])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1

In [45]:
import pandas as pd

# Create DataFrame
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

# =====================================================
# 1. Filter by Single Condition
# =====================================================
print("\n1. Salary > 50000")
print(df[df["Salary"] > 50000])

# =====================================================
# 2. Filter by Multiple Conditions (AND)
# =====================================================
print("\n2. Salary > 50000 AND Experience > 4")
print(df[(df["Salary"] > 50000) & (df["Experience"] > 4)])

# =====================================================
# 3. Filter by Multiple Conditions (OR)
# =====================================================
print("\n3. Department = IT OR HR")
print(df[(df["Department"] == "IT") | (df["Department"] == "HR")])

# =====================================================
# 4. Filter Using isin()
# =====================================================
print("\n4. Department in ['IT', 'Finance']")
print(df[df["Department"].isin(["IT", "Finance"])])

# =====================================================
# 5. Filter Using Between()
# =====================================================
print("\n5. Salary Between 45000 and 60000")
print(df[df["Salary"].between(45000, 60000)])

# =====================================================
# 6. Filter Using String Matching
# =====================================================
print("\n6. Names Starting with 'P'")
print(df[df["Name"].str.startswith("P")])

Original DataFrame
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

1. Salary > 50000
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
2     203  Karan    Finance   65000           6
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

2. Salary > 50000 AND Experience > 4
   Emp_ID   Name Department  Salary  Experience
2     203  Karan    Finance   65000           6
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

3. Department = IT OR HR
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
5     206  Pooja         IT   70000           8

4. Department in ['IT', 'Finance']
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
2     203  Karan    Finance   65000           6
5     206  Pooja         IT   70000           8

5. Salary Between 45000 and 60000
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5

6. Names Starting with 'P'
   Emp_ID   Name Department  Salary  Experience
1     202  Priya         HR   42000           2
5     206  Pooja         IT   70000           8

# Sorting Operations in Pandas

1. Sort by Salary (Ascending)
2. Sort by Salary (Descending)
3. Sort by Name (A-Z)
4. Sort by Name (Z-A)
5. Sort by Department
6. Sort by Experience
7. Sort by Experience (Descending)
8. Sort by Multiple Columns
9. Sort by Multiple Columns with Different Orders
10. Sort by Three Columns
11. Sort by Index (Ascending)
12. Sort by Index (Descending)
13. Sort and Reset Index
14. Inplace Sorting
15. Stable Sorting (mergesort)

In [47]:
# sorting
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# sorting ascending
print(df.sort_values("Salary",ascending=False))

# two cols
print(df.sort_values(["Salary","Experience"]))

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
5     106  Neha         HR   52000           3
0     101  Amit         IT   50000           2
4     105  John      Sales   48000           1
1     102  Riya         HR   45000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5

In [48]:
import pandas as pd

# Create DataFrame
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Rahul", "Priya", "Karan", "Sneha", "Aman", "Pooja"],
    "Department": ["IT", "HR", "Finance", "Marketing", "Sales", "IT"],
    "Salary": [55000, 42000, 65000, 48000, 53000, 70000],
    "Experience": [3, 2, 6, 4, 5, 8]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)


# 1. Sort by Salary (Ascending)

print("\n1. Sort by Salary (Ascending)")
print(df.sort_values(by="Salary"))


# 2. Sort by Salary (Descending)

print("\n2. Sort by Salary (Descending)")
print(df.sort_values(by="Salary", ascending=False))

Original DataFrame
   Emp_ID   Name Department  Salary  Experience
0     201  Rahul         IT   55000           3
1     202  Priya         HR   42000           2
2     203  Karan    Finance   65000           6
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
5     206  Pooja         IT   70000           8

1. Sort by Salary (Ascending)
   Emp_ID   Name Department  Salary  Experience
1     202  Priya         HR   42000           2
3     204  Sneha  Marketing   48000           4
4     205   Aman      Sales   53000           5
0     201  Rahul         IT   55000           3
2     203  Karan    Finance   65000           6
5     206  Pooja         IT   70000           8

2. Sort by Salary (Descending)
   Emp_ID   Name Department  Salary  Experience
5     206  Pooja         IT   70000           8
2     203  Karan    Finance   65000           6
0     201  Rahul         IT   55000           3
4     205   Aman      Sales   53000           5
3     204  Sneha  Marketing   48000           4
1     202  Priya         HR   42000           2

In [50]:
#practice
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [51]:
#practice
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df


print("Head")
print(df.head())

print("\nTail")
print(df.tail())

print("\nInfo")
df.info()

print("\nDescribe")
print(df.describe())

print("\nShape")
print(df.shape)

print("\nColumns")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nRename Column")
df.rename(columns={"name":"student_name"}, inplace=True)
print(df.head())

Head
      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

Tail
       name  gender  physics  maths  english
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     object
 1   gender   14 non-null     object
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), object(2)
memory usage: 692.0+ bytes

Describe
          physics       maths     english
count   14.000000   14.000000   14.000000
mean    65.857143   71.285714   69.857143
std     26.046872   24.237379   21.205432
min     12.000000   25.000000   23.000000
25%     56.000000   48.250000   67.000000
50%     69.000000   79.000000   74.000000
75%     85.500000   89.750000   78.000000
max    100.000000  100.000000  100.000000

Shape
(14, 5)

Columns
Index(['name', 'gender', 'physics', 'maths', 'english'], dtype='object')

Data Types
name       object
gender     object
physics     int64
maths       int64
english     int64
dtype: object

Rename Column
  student_name  gender  physics  maths  english
0         arun    Male       88     87       78
1       rajesh    Male       96    100       95
2      moorthy    Male       89     90       70
3         raja    Male       30     25       40
4         usha  Female       67     45       78

In [54]:
#practice
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df

#row operations

print("\n1. loc[] - Get Single Value")
print(df.loc[0, "name"])

print("\n2. loc[] - Get Complete Row")
print(df.loc[2])


print("\n3. loc[] - Get Multiple Rows")
print(df.loc[[1, 3]])


print("\n4. loc[] - Get Multiple Rows and Columns")
print(df.loc[[0, 2], ["name", "maths"]])

print("\n5. iloc[] - Get Single Value")
print(df.iloc[1, 2])

print("\n6. iloc[] - Get Complete Row")
print(df.iloc[4])

print("\n7. iloc[] - Get Multiple Rows")
print(df.iloc[[0, 5]])

print("\n8. iloc[] - Get Multiple Rows and Columns")
print(df.iloc[[1, 4], [1, 3]])


print("\n9. iloc[] - Get First Column from Selected Rows")
print(df.iloc[[0, 2], [0]])


print("\n10. iloc[] - Get Column as Series")
print(df.iloc[[1, 2], 0])

print("\n11. iloc[] - Slice Rows")
print(df.iloc[0:3])

1. loc[] - Get Single Value
arun

2. loc[] - Get Complete Row
name       moorthy
gender        Male
physics         89
maths           90
english         70
Name: 2, dtype: object

3. loc[] - Get Multiple Rows
     name gender  physics  maths  english
1  rajesh   Male       96    100       95
3    raja   Male       30     25       40

4. loc[] - Get Multiple Rows and Columns
      name  maths
0     arun     87
2  moorthy     90

5. iloc[] - Get Single Value
96

6. iloc[] - Get Complete Row
name         usha
gender     Female
physics        67
maths          45
english        78
Name: 4, dtype: object

7. iloc[] - Get Multiple Rows
    name  gender  physics  maths  english
0   arun    Male       88     87       78
5  priya  Female       56     46       78

8. iloc[] - Get Multiple Rows and Columns
   gender  maths
1    Male    100
4  Female     45

9. iloc[] - Get First Column from Selected Rows
      name
0     arun
2  moorthy

10. iloc[] - Get Column as Series
1     rajesh
2    moorthy
Name: name, dtype: object

11. iloc[] - Slice Rows
      name gender  physics  maths  english
0     arun   Male       88     87       78
1   rajesh   Male       96    100       95
2  moorthy   Male       89     90       70

In [56]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df
print(df["name"])

print(df[["name","maths"]])

df["Bonus"] = 100

print(df.head())

df["Bonus"] = df["Bonus"] + 50

print(df.head())

df.drop("Bonus", axis=1, inplace=True)

print(df.head())

0        arun
1      rajesh
2     moorthy
3        raja
4        usha
5       priya
6      Sundar
7     Kavitha
8      Dinesh
9        Hema
10      Gowri
11        Ram
12    Murugan
13    Jenifer
Name: name, dtype: object
       name  maths
0      arun     87
1    rajesh    100
2   moorthy     90
3      raja     25
4      usha     45
5     priya     46
6    Sundar     67
7   Kavitha     71
8    Dinesh     45
9      Hema     90
10    Gowri    100
11      Ram     55
12  Murugan     89
13  Jenifer     88
      name  gender  physics  maths  english  Bonus
0     arun    Male       88     87       78    100
1   rajesh    Male       96    100       95    100
2  moorthy    Male       89     90       70    100
3     raja    Male       30     25       40    100
4     usha  Female       67     45       78    100
      name  gender  physics  maths  english  Bonus
0     arun    Male       88     87       78    150
1   rajesh    Male       96    100       95    150
2  moorthy    Male       89     90       70    150
3     raja    Male       30     25       40    150
4     usha  Female       67     45       78    150
      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

In [59]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df
# Filter Operations

print(df[df["maths"]>80])

print(df[df["maths"]>=70])

print(df[(df["maths"]>80) & (df["gender"]=="Male")])

print(df[(df["gender"]=="Male") | (df["gender"]=="Female")])

print(df[df["maths"].between(70,90)])

print(df[df["name"].str.startswith("A")])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
12  Murugan   Male       34     89       78
       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name  gender  physics  maths  english
0      arun    Male       88     87       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
Empty DataFrame
Columns: [name, gender, physics, maths, english]
Index: []

In [61]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df
# Sorting


print(df.sort_values(by="name")) # Changed 'student_name' to 'name'

print(df.sort_values(by="name",ascending=False)) # Changed 'student_name' to 'name'

print(df.sort_values(by="maths")) # Changed 'age' to 'maths'

print(df.sort_values(by="maths",ascending=False)) # Changed 'age' to 'maths'

print(df.sort_values(by=["gender","maths"])) # Changed 'age' to 'maths'

print(df.sort_values(by=["gender","maths"],ascending=[True,False])) # Changed 'age' to 'maths'

print(df.sort_index())

print(df.sort_index(ascending=False))

print(df.sort_values(by="maths",ignore_index=True)) # Changed 'age' to 'maths'

       name  gender  physics  maths  english
8    Dinesh    Male       56     45       67
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
13  Jenifer  Female       67     88       90
7   Kavitha  Female       78     71       67
12  Murugan    Male       34     89       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
0      arun    Male       88     87       78
2   moorthy    Male       89     90       70
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
4      usha  Female       67     45       78
       name  gender  physics  maths  english
4      usha  Female       67     45       78
1    rajesh    Male       96    100       95
3      raja    Male       30     25       40
5     priya  Female       56     46       78
2   moorthy    Male       89     90       70
0      arun    Male       88     87       78
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
7   Kavitha  Female       78     71       67
13  Jenifer  Female       67     88       90
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
8    Dinesh    Male       56     45       67
       name  gender  physics  maths  english
3      raja    Male       30     25       40
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
5     priya  Female       56     46       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
0      arun    Male       88     87       78
13  Jenifer  Female       67     88       90
12  Murugan    Male       34     89       78
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100
       name  gender  physics  maths  english
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0      arun    Male       88     87       78
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
5     priya  Female       56     46       78
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40
       name  gender  physics  maths  english
4      usha  Female       67     45       78
5     priya  Female       56     46       78
7   Kavitha  Female       78     71       67
13  Jenifer  Female       67     88       90
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
3      raja    Male       30     25       40
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
1    rajesh    Male       96    100       95
       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
13  Jenifer  Female       67     88       90
7   Kavitha  Female       78     71       67
5     priya  Female       56     46       78
4      usha  Female       67     45       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
12  Murugan    Male       34     89       78
0      arun    Male       88     87       78
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40
       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name  gender  physics  maths  english
13  Jenifer  Female       67     88       90
12  Murugan    Male       34     89       78
11      Ram    Male       78     55       47
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
8    Dinesh    Male       56     45       67
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
5     priya  Female       56     46       78
4      usha  Female       67     45       78
3      raja    Male       30     25       40
2   moorthy    Male       89     90       70
1    rajesh    Male       96    100       95
0      arun    Male       88     87       78
       name  gender  physics  maths  english
0      raja    Male       30     25       40
1      usha  Female       67     45       78
2    Dinesh    Male       56     45       67
3     priya  Female       56     46       78
4       Ram    Male       78     55       47
5    Sundar    Male       12     67       67
6   Kavitha  Female       78     71       67
7      arun    Male       88     87       78
8   Jenifer  Female       67     88       90
9   Murugan    Male       34     89       78
10     Hema  Female       71     90       23
11  moorthy    Male       89     90       70
12   rajesh    Male       96    100       95
13    Gowri  Female      100    100      100

In [62]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df

# Missing Values


print(df.isnull())

print(df.isnull().sum())

print(df.dropna())

print(df.fillna(0))

     name  gender  physics  maths  english
0   False   False    False  False    False
1   False   False    False  False    False
2   False   False    False  False    False
3   False   False    False  False    False
4   False   False    False  False    False
5   False   False    False  False    False
6   False   False    False  False    False
7   False   False    False  False    False
8   False   False    False  False    False
9   False   False    False  False    False
10  False   False    False  False    False
11  False   False    False  False    False
12  False   False    False  False    False
13  False   False    False  False    False
name       0
gender     0
physics    0
maths      0
english    0
dtype: int64
       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90